# this is the only kubectl apply you'll have to do
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argocd
    namespace: argocd
spec:
    project: default # what are the projects?
    source:
        repoURL: https://github.com/Drikkie1608/kluster-grindyoung
        targetRevision: HEAD
        path: applications # Foldername
    destination:
        server: "https://kubernetes.default.svc"
        namespace: applications # namespace where the applications will be deployed
    syncPolicy:
        syncOptions:
            - CreateNamespace=true

        automated: # every 3 minutes, can be done with webhook #future
            prune: true
            selfHeal: true
