# installing argocd
# kubectl create namespace argocd
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# kubectl apply this file
#
# Connecting to UI
# kubectl port-forward service/argocd-server -n argocd 8080:443
# kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argocd
    namespace: argocd
spec:
    project: default # what are the projects?
    source:
        repoURL: https://github.com/Drikkie1608/kluster-grindyoung
        targetRevision: HEAD
        path: applications # Foldername
    destination:
        server: "https://kubernetes.default.svc"
        namespace: applications # namespace where the applications will be deployed
    syncPolicy:
        syncOptions:
            - CreateNamespace=true

        automated: # every 3 minutes, can be done with webhook #future
            prune: true
            selfHeal: true
