apiVersion: apps/v1
kind: Deployment
metadata:
    name: website-deployment
spec:
    replicas: 1 # You can adjust the number of replicas as needed
    selector:
        matchLabels:
            app: website
    template:
        metadata:
            labels:
                app: website
        spec:
            containers:
                - name: website
                  image: drikkie/under-construction-grindyoung:latest
                  ports:
                      - containerPort: 80 # Port the container is listening on

---
apiVersion: v1
kind: Service
metadata:
    name: website-service
spec:
    selector:
        app: website
    ports:
        - port: 80
          targetPort: 80
