apiVersion: apps/v1
kind: Deployment
metadata:
    name: pdf-pptx-converter
spec:
    replicas: 3 # You can adjust the number of replicas as needed
    selector:
        matchLabels:
            app: pdf-pptx-converter
    template:
        metadata:
            labels:
                app: pdf-pptx-converter
        spec:
            containers:
                - name: pdf-pptx-converter
                  image: drikkie/pdf-pptx-converter
                  ports:
                      - containerPort: 8080 # Port the container is listening on

---
apiVersion: v1
kind: Service
metadata:
    name: pdf-pptx-converter-service
spec:
    selector:
        app: pdf-pptx-converter
    ports:
        - port: 80
          targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-powerpoint
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0" # future: limit upload file size
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: "Authentication required"
spec:
    ingressClassName: nginx
    rules:
        - host: "powerpoint.grindyoung.com"
          http:
              paths:
                  - pathType: Prefix
                    path: "/"
                    backend:
                        service:
                            name: pdf-pptx-converter-service
                            port:
                                number: 80
